---
abstract: 'Reports specific ifconfig values for a network interface'
author:
  - 'Bruce Burch <bcb12001@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Int-Stats
no_index:
  directory:
    - t
    - inc
requires: {}
version: 2.1
